
package GUI;

import java.awt.*;
import javax.swing.*;
/**
 *
 * @author shaosh
 */
public class AdminUserList extends javax.swing.JFrame {

    /**
     * Creates new form DocSignIn
     */
    public AdminUserList() {
        initComponents();
        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
	int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
	this.setLocation((screenWidth - this.getSize().width) / 2,(screenHeight - this.getSize().height) / 2); 
    }
    public void CreateDoctorVisible(){
        this.setVisible(true);		
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog2 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jDialog3 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jDialog4 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jDialog5 = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jDialog6 = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        docSignin = new javax.swing.JPanel();
        signButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        signButton1 = new javax.swing.JButton();
        signButton2 = new javax.swing.JButton();
        signButton3 = new javax.swing.JButton();
        signButton4 = new javax.swing.JButton();

        jDialog2.setTitle("Attention");
        jDialog2.setIconImage(null);
        jDialog2.setPreferredSize(new java.awt.Dimension(450, 200));
        jDialog2.setResizable(false);
        jDialog2.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setText("Do you still want to continue?");
        jDialog2.getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 60, 290, 30);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("The user's password will be reset. ");
        jDialog2.getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 30, 220, 30);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton1.setText("Confirm");
        jDialog2.getContentPane().add(jButton1);
        jButton1.setBounds(80, 110, 100, 30);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton2.setText("Cancel");
        jDialog2.getContentPane().add(jButton2);
        jButton2.setBounds(270, 110, 100, 30);

        idLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        idLabel.setText("Result");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Name    UserID" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jDialog3.setTitle("Attention");
        jDialog3.setIconImage(null);
        jDialog3.setResizable(false);
        jDialog3.getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setText("No such user.");
        jDialog3.getContentPane().add(jLabel4);
        jLabel4.setBounds(55, 30, 90, 30);

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton3.setText("Confirm");
        jDialog3.getContentPane().add(jButton3);
        jButton3.setBounds(50, 80, 100, 30);

        jDialog4.setTitle("Attention");
        jDialog4.setIconImage(null);
        jDialog4.setModal(true);
        jDialog4.setPreferredSize(new java.awt.Dimension(450, 200));
        jDialog4.setResizable(false);
        jDialog4.getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setText("Do you still want to continue?");
        jDialog4.getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 60, 290, 30);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel5.setText("The user account will be lockout. ");
        jDialog4.getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 30, 220, 30);

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton4.setText("Confirm");
        jDialog4.getContentPane().add(jButton4);
        jButton4.setBounds(80, 110, 100, 30);

        jButton5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton5.setText("Cancel");
        jDialog4.getContentPane().add(jButton5);
        jButton5.setBounds(270, 110, 100, 30);

        jDialog5.setTitle("Attention");
        jDialog5.setIconImage(null);
        jDialog5.setModal(true);
        jDialog5.setPreferredSize(new java.awt.Dimension(450, 200));
        jDialog5.setResizable(false);
        jDialog5.getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setText("Do you still want to continue?");
        jDialog5.getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 60, 290, 30);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setText("The user account will be unlocked. ");
        jDialog5.getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 30, 220, 30);

        jButton6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton6.setText("Confirm");
        jDialog5.getContentPane().add(jButton6);
        jButton6.setBounds(80, 110, 100, 30);

        jButton7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton7.setText("Cancel");
        jDialog5.getContentPane().add(jButton7);
        jButton7.setBounds(270, 110, 100, 30);

        jDialog6.setTitle("Attention");
        jDialog6.setIconImage(null);
        jDialog6.setModal(true);
        jDialog6.setPreferredSize(new java.awt.Dimension(450, 200));
        jDialog6.setResizable(false);
        jDialog6.getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel8.setText("Do you still want to continue?");
        jDialog6.getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 60, 290, 30);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel9.setText("The two user accounts will be merged. ");
        jDialog6.getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 30, 220, 30);

        jButton8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton8.setText("Confirm");
        jDialog6.getContentPane().add(jButton8);
        jButton8.setBounds(80, 110, 100, 30);

        jButton9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton9.setText("Cancel");
        jDialog6.getContentPane().add(jButton9);
        jButton9.setBounds(270, 110, 100, 30);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Users Found");
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(450, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        docSignin.setMaximumSize(new java.awt.Dimension(450, 300));
        docSignin.setMinimumSize(new java.awt.Dimension(0, 0));
        docSignin.setLayout(null);

        signButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        signButton.setText("Confirm Merger");
        signButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signButtonActionPerformed(evt);
            }
        });
        docSignin.add(signButton);
        signButton.setBounds(320, 230, 120, 25);

        cancelButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        docSignin.add(cancelButton);
        cancelButton.setBounds(320, 200, 120, 25);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Gender", "ID", "Type"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        docSignin.add(jScrollPane3);
        jScrollPane3.setBounds(10, 10, 430, 180);

        signButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        signButton1.setText("Lockout");
        signButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signButton1ActionPerformed(evt);
            }
        });
        docSignin.add(signButton1);
        signButton1.setBounds(10, 200, 120, 25);

        signButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        signButton2.setText("Reset Password");
        signButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signButton2ActionPerformed(evt);
            }
        });
        docSignin.add(signButton2);
        signButton2.setBounds(10, 230, 120, 25);

        signButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        signButton3.setText("Unlock");
        signButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signButton3ActionPerformed(evt);
            }
        });
        docSignin.add(signButton3);
        signButton3.setBounds(170, 200, 120, 25);

        signButton4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        signButton4.setText("Merger");
        signButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signButton4ActionPerformed(evt);
            }
        });
        docSignin.add(signButton4);
        signButton4.setBounds(170, 230, 120, 25);

        getContentPane().add(docSignin);
        docSignin.setBounds(0, 0, 450, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        Welcome welcome = new Welcome();
	welcome.WelcomeVisible();
	this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void signButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signButtonActionPerformed
    //*******************************
    //need coding
    //*******************************	
    	
    }//GEN-LAST:event_signButtonActionPerformed

    private void signButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signButton1ActionPerformed

    private void signButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signButton2ActionPerformed

    private void signButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signButton3ActionPerformed

    private void signButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetPermission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetPermission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetPermission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetPermission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUserList().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel docSignin;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JDialog jDialog5;
    private javax.swing.JDialog jDialog6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton signButton;
    private javax.swing.JButton signButton1;
    private javax.swing.JButton signButton2;
    private javax.swing.JButton signButton3;
    private javax.swing.JButton signButton4;
    // End of variables declaration//GEN-END:variables
}
