
package GUI;

import java.awt.*;
import javax.swing.*;
/**
 *
 * @author shaosh
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form DocSignIn
     */
    public ChangePassword() {
        initComponents();
        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
	int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
	this.setLocation((screenWidth - this.getSize().width) / 2,(screenHeight - this.getSize().height) / 2); 
    }
    public void ChangePasswordVisible(){
        this.setVisible(true);		
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        reminderLabel = new javax.swing.JLabel();
        oldLabel = new javax.swing.JLabel();
        newLabel = new javax.swing.JLabel();
        confirmLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        oldField = new javax.swing.JPasswordField();
        newField = new javax.swing.JPasswordField();
        confirmField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change Password");
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(450, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        panel.setMaximumSize(new java.awt.Dimension(450, 300));
        panel.setMinimumSize(new java.awt.Dimension(0, 0));
        panel.setPreferredSize(new java.awt.Dimension(450, 300));
        panel.setLayout(null);

        reminderLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        reminderLabel.setText("You may want to change your default password");
        panel.add(reminderLabel);
        reminderLabel.setBounds(75, 0, 300, 30);

        oldLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        oldLabel.setText("Old Password");
        panel.add(oldLabel);
        oldLabel.setBounds(75, 50, 100, 30);

        newLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        newLabel.setText("New Password");
        panel.add(newLabel);
        newLabel.setBounds(75, 100, 100, 30);

        confirmLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        confirmLabel.setText("Confirm");
        panel.add(confirmLabel);
        confirmLabel.setBounds(75, 150, 100, 30);

        submitButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        panel.add(submitButton);
        submitButton.setBounds(75, 200, 100, 30);

        cancelButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        panel.add(cancelButton);
        cancelButton.setBounds(275, 200, 100, 30);
        panel.add(oldField);
        oldField.setBounds(175, 50, 200, 30);
        panel.add(newField);
        newField.setBounds(175, 100, 200, 30);
        panel.add(confirmField);
        confirmField.setBounds(175, 150, 200, 30);

        getContentPane().add(panel);
        panel.setBounds(0, 0, 450, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        //*******************************
	//need coding
	//*******************************	
	//show password update success or fail
	//if this is a doctor, go to search
	//if this is a patient, go to history       
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        Welcome welcome =  new Welcome();
	welcome.WelcomeVisible();
	this.setVisible(false);        
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPasswordField confirmField;
    private javax.swing.JLabel confirmLabel;
    private javax.swing.JPasswordField newField;
    private javax.swing.JLabel newLabel;
    private javax.swing.JPasswordField oldField;
    private javax.swing.JLabel oldLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel reminderLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
