
package GUI;

import java.awt.*;
import javax.swing.*;
/**
 *
 * @author shaosh
 */
public class Find extends javax.swing.JFrame {

    /**
     * Creates new form DocSignIn
     */
    public Find() {
        initComponents();
        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
	int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
	this.setLocation((screenWidth - this.getSize().width) / 2,(screenHeight - this.getSize().height) / 2); 
    }
    public void CreateDoctorVisible(){
        this.setVisible(true);		
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jDialog2 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jDialog3 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        docSignin = new javax.swing.JPanel();
        pwLabel = new javax.swing.JLabel();
        signButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        pwLabel2 = new javax.swing.JLabel();
        pwField = new javax.swing.JTextField();
        pwLabel3 = new javax.swing.JLabel();
        idField1 = new javax.swing.JTextField();
        idLabel1 = new javax.swing.JLabel();
        idLabel2 = new javax.swing.JLabel();

        jDialog2.setTitle("Attention");
        jDialog2.setIconImage(null);
        jDialog2.setResizable(false);
        jDialog2.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setText("Do you still want to continue?");
        jDialog2.getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 60, 290, 30);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("Doctors with the same profile have already existed.");
        jDialog2.getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 30, 290, 30);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton1.setText("Confirm");
        jDialog2.getContentPane().add(jButton1);
        jButton1.setBounds(80, 110, 100, 30);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton2.setText("Cancel");
        jDialog2.getContentPane().add(jButton2);
        jButton2.setBounds(270, 110, 100, 30);

        idLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        idLabel.setText("Result");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Name    UserID" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jDialog3.setTitle("Attention");
        jDialog3.setIconImage(null);
        jDialog3.setPreferredSize(new java.awt.Dimension(200, 180));
        jDialog3.setResizable(false);
        jDialog3.getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setText("No such user.");
        jDialog3.getContentPane().add(jLabel4);
        jLabel4.setBounds(55, 30, 90, 30);

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton3.setText("Confirm");
        jDialog3.getContentPane().add(jButton3);
        jButton3.setBounds(50, 80, 100, 30);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Find");
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(450, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        docSignin.setMaximumSize(new java.awt.Dimension(450, 300));
        docSignin.setMinimumSize(new java.awt.Dimension(0, 0));
        docSignin.setLayout(null);

        pwLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        pwLabel.setText("Last Name");
        docSignin.add(pwLabel);
        pwLabel.setBounds(70, 80, 70, 30);

        signButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        signButton.setText("Find");
        signButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signButtonActionPerformed(evt);
            }
        });
        docSignin.add(signButton);
        signButton.setBounds(70, 200, 100, 30);

        cancelButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        docSignin.add(cancelButton);
        cancelButton.setBounds(280, 200, 100, 30);

        idField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        docSignin.add(idField);
        idField.setBounds(160, 80, 220, 30);

        jComboBox1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jComboBox1.setMaximumRowCount(12);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        docSignin.add(jComboBox1);
        jComboBox1.setBounds(160, 120, 70, 30);

        jComboBox2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jComboBox2.setMaximumRowCount(31);
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        docSignin.add(jComboBox2);
        jComboBox2.setBounds(250, 120, 50, 30);

        jComboBox3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jComboBox3.setMaximumRowCount(100);
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1960", "Item 2", "Item 3", "Item 4" }));
        docSignin.add(jComboBox3);
        jComboBox3.setBounds(320, 120, 60, 30);

        pwLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        pwLabel2.setText("Birthday");
        docSignin.add(pwLabel2);
        pwLabel2.setBounds(70, 120, 70, 30);

        pwField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        pwField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwFieldActionPerformed(evt);
            }
        });
        docSignin.add(pwField);
        pwField.setBounds(160, 40, 220, 30);

        pwLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        pwLabel3.setText("User ID");
        docSignin.add(pwLabel3);
        pwLabel3.setBounds(70, 160, 70, 30);

        idField1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        docSignin.add(idField1);
        idField1.setBounds(160, 160, 220, 30);

        idLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        idLabel1.setForeground(new java.awt.Color(255, 0, 0));
        idLabel1.setText("No such user. Please modify the search information.");
        docSignin.add(idLabel1);
        idLabel1.setBounds(70, 0, 290, 30);

        idLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        idLabel2.setText("First Name");
        docSignin.add(idLabel2);
        idLabel2.setBounds(70, 40, 70, 30);

        getContentPane().add(docSignin);
        docSignin.setBounds(0, 0, 450, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        Welcome welcome = new Welcome();
	welcome.WelcomeVisible();
	this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void signButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signButtonActionPerformed
    //*******************************
    //need coding
    //*******************************	
    	
    }//GEN-LAST:event_signButtonActionPerformed

    private void pwFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetPermission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetPermission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetPermission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetPermission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Find().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel docSignin;
    private javax.swing.JTextField idField;
    private javax.swing.JTextField idField1;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idLabel1;
    private javax.swing.JLabel idLabel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pwField;
    private javax.swing.JLabel pwLabel;
    private javax.swing.JLabel pwLabel2;
    private javax.swing.JLabel pwLabel3;
    private javax.swing.JButton signButton;
    // End of variables declaration//GEN-END:variables
}
