

package GUI;
import java.awt.*;
/**
 *
 * @author shaosh
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
	int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
	this.setLocation((screenWidth - this.getSize().width) / 2,(screenHeight - this.getSize().height) / 2); 
    }
    public void WelcomeVisible(){
        this.setVisible(true);		
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        docButton = new javax.swing.JButton();
        patientButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Well-Check Clinic");
        setMaximumSize(new java.awt.Dimension(450, 300));
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(450, 300));
        setResizable(false);

        panel.setLayout(null);

        label.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Welcome to Well-Check Clinic!");
        label.setPreferredSize(new java.awt.Dimension(200, 30));
        panel.add(label);
        label.setBounds(40, 60, 365, 30);

        infoLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        infoLabel.setText("v1.0       by Team12");
        panel.add(infoLabel);
        infoLabel.setBounds(140, 110, 150, 21);

        docButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        docButton.setText("Doctor");
        docButton.setPreferredSize(new java.awt.Dimension(100, 30));
        docButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                docButtonActionPerformed(evt);
            }
        });
        panel.add(docButton);
        docButton.setBounds(40, 190, 100, 30);

        patientButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        patientButton.setText("Patient");
        patientButton.setPreferredSize(new java.awt.Dimension(100, 30));
        patientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientButtonActionPerformed(evt);
            }
        });
        panel.add(patientButton);
        patientButton.setBounds(180, 190, 100, 30);

        adminButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        adminButton.setText("Admin");
        adminButton.setPreferredSize(new java.awt.Dimension(100, 30));
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });
        panel.add(adminButton);
        adminButton.setBounds(310, 190, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void docButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_docButtonActionPerformed
        DocSignIn docSignIn = new DocSignIn();
	docSignIn.DocSignVisible();
	this.setVisible(false);
    }//GEN-LAST:event_docButtonActionPerformed

    private void patientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientButtonActionPerformed
        PatientSignIn patientSignIn = new PatientSignIn();
	patientSignIn.PatientSignVisible();
	this.setVisible(false);
    }//GEN-LAST:event_patientButtonActionPerformed

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_adminButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton docButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel label;
    private javax.swing.JPanel panel;
    private javax.swing.JButton patientButton;
    // End of variables declaration//GEN-END:variables
}
