
package GUI;

import java.awt.*;
import javax.swing.*;
/**
 *
 * @author shaosh
 */
public class ConfirmMerge extends javax.swing.JFrame {

    /**
     * Creates new form DocSignIn
     */
    public ConfirmMerge() {
        initComponents();
        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
	int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
	this.setLocation((screenWidth - this.getSize().width) / 2,(screenHeight - this.getSize().height) / 2); 
    }
    public void ConfirmMergeVisible(){
        this.setVisible(true);		
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mergeConfirmDialog = new javax.swing.JDialog();
        mergeConfirmLabel2 = new javax.swing.JLabel();
        mergeConfirmLabel1 = new javax.swing.JLabel();
        confirmMergeButton = new javax.swing.JButton();
        cancelMergeButton = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jDialog3 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jDialog4 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jDialog5 = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jDialog6 = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        confirmDialog = new javax.swing.JDialog();
        confirmPanel = new javax.swing.JPanel();
        confirmDialogButton = new javax.swing.JButton();
        confirmInfoLabel = new javax.swing.JLabel();
        docSignin = new javax.swing.JPanel();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        secondAccountTable = new javax.swing.JTable();
        firstAccountLabel = new javax.swing.JLabel();
        reminderLabel = new javax.swing.JLabel();

        mergeConfirmDialog.setTitle("Attention");
        mergeConfirmDialog.setIconImage(null);
        mergeConfirmDialog.setResizable(false);
        mergeConfirmDialog.getContentPane().setLayout(null);

        mergeConfirmLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        mergeConfirmLabel2.setText("Do you still want to continue?");
        mergeConfirmDialog.getContentPane().add(mergeConfirmLabel2);
        mergeConfirmLabel2.setBounds(80, 60, 290, 30);

        mergeConfirmLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        mergeConfirmLabel1.setText("These two accounts will be merged. ");
        mergeConfirmDialog.getContentPane().add(mergeConfirmLabel1);
        mergeConfirmLabel1.setBounds(80, 30, 220, 30);

        confirmMergeButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        confirmMergeButton.setText("Confirm");
        confirmMergeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmMergeButtonActionPerformed(evt);
            }
        });
        mergeConfirmDialog.getContentPane().add(confirmMergeButton);
        confirmMergeButton.setBounds(80, 110, 100, 30);

        cancelMergeButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cancelMergeButton.setText("Cancel");
        cancelMergeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelMergeButtonActionPerformed(evt);
            }
        });
        mergeConfirmDialog.getContentPane().add(cancelMergeButton);
        cancelMergeButton.setBounds(270, 110, 100, 30);

        idLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        idLabel.setText("Result");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Name    UserID" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jDialog3.setTitle("Attention");
        jDialog3.setIconImage(null);
        jDialog3.setResizable(false);
        jDialog3.getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setText("No such user.");
        jDialog3.getContentPane().add(jLabel4);
        jLabel4.setBounds(55, 30, 90, 30);

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton3.setText("Confirm");
        jDialog3.getContentPane().add(jButton3);
        jButton3.setBounds(50, 80, 100, 30);

        jDialog4.setTitle("Attention");
        jDialog4.setIconImage(null);
        jDialog4.setModal(true);
        jDialog4.setResizable(false);
        jDialog4.getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setText("Do you still want to continue?");
        jDialog4.getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 60, 290, 30);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel5.setText("The user account will be lockout. ");
        jDialog4.getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 30, 220, 30);

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton4.setText("Confirm");
        jDialog4.getContentPane().add(jButton4);
        jButton4.setBounds(80, 110, 100, 30);

        jButton5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton5.setText("Cancel");
        jDialog4.getContentPane().add(jButton5);
        jButton5.setBounds(270, 110, 100, 30);

        jDialog5.setTitle("Attention");
        jDialog5.setIconImage(null);
        jDialog5.setModal(true);
        jDialog5.setResizable(false);
        jDialog5.getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setText("Do you still want to continue?");
        jDialog5.getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 60, 290, 30);

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setText("The user account will be unlocked. ");
        jDialog5.getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 30, 220, 30);

        jButton6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton6.setText("Confirm");
        jDialog5.getContentPane().add(jButton6);
        jButton6.setBounds(80, 110, 100, 30);

        jButton7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton7.setText("Cancel");
        jDialog5.getContentPane().add(jButton7);
        jButton7.setBounds(270, 110, 100, 30);

        jDialog6.setTitle("Attention");
        jDialog6.setIconImage(null);
        jDialog6.setModal(true);
        jDialog6.setResizable(false);
        jDialog6.getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel8.setText("Do you still want to continue?");
        jDialog6.getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 60, 290, 30);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel9.setText("The two user accounts will be merged. ");
        jDialog6.getContentPane().add(jLabel9);
        jLabel9.setBounds(80, 30, 220, 30);

        jButton8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton8.setText("Confirm");
        jDialog6.getContentPane().add(jButton8);
        jButton8.setBounds(80, 110, 100, 30);

        jButton9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton9.setText("Cancel");
        jDialog6.getContentPane().add(jButton9);
        jButton9.setBounds(270, 110, 100, 30);

        confirmDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        confirmDialog.setTitle("Attention");
        confirmDialog.setAlwaysOnTop(true);
        confirmDialog.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        confirmDialog.setIconImage(null);
        confirmDialog.setName("completeDialog"); // NOI18N
        confirmDialog.setResizable(false);
        confirmDialog.getContentPane().setLayout(null);

        confirmPanel.setMaximumSize(new java.awt.Dimension(285, 190));
        confirmPanel.setPreferredSize(new java.awt.Dimension(285, 190));
        confirmPanel.setLayout(null);

        confirmDialogButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        confirmDialogButton.setText("Confirm");
        confirmDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmDialogButtonActionPerformed(evt);
            }
        });
        confirmPanel.add(confirmDialogButton);
        confirmDialogButton.setBounds(90, 80, 100, 30);

        confirmInfoLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        confirmPanel.add(confirmInfoLabel);
        confirmInfoLabel.setBounds(70, 30, 150, 30);

        confirmDialog.getContentPane().add(confirmPanel);
        confirmPanel.setBounds(0, 0, 285, 190);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Confirm Merge");
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(450, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        docSignin.setMaximumSize(new java.awt.Dimension(450, 300));
        docSignin.setMinimumSize(new java.awt.Dimension(0, 0));
        docSignin.setLayout(null);

        confirmButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        confirmButton.setText("Confirm Merger");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        docSignin.add(confirmButton);
        confirmButton.setBounds(70, 210, 125, 30);

        cancelButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        docSignin.add(cancelButton);
        cancelButton.setBounds(260, 210, 125, 30);

        secondAccountTable.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        secondAccountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Gender", "ID", "Type"
            }
        ));
        secondAccountTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(secondAccountTable);

        docSignin.add(jScrollPane3);
        jScrollPane3.setBounds(10, 60, 430, 130);

        firstAccountLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        firstAccountLabel.setText("FirstAccount");
        docSignin.add(firstAccountLabel);
        firstAccountLabel.setBounds(210, 30, 90, 15);

        reminderLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        reminderLabel.setText("Select one account to merge with: ");
        docSignin.add(reminderLabel);
        reminderLabel.setBounds(10, 30, 210, 15);

        getContentPane().add(docSignin);
        docSignin.setBounds(0, 0, 450, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        UserList userList = new UserList();
        userList.UserListVisible();
	this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        if(secondAccountTable.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(null, "Please select one account!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
        else{           
            int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
            int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
            mergeConfirmDialog.setSize(450, 200);
            mergeConfirmDialog.setLocation((screenWidth - mergeConfirmDialog.getSize().width) / 2,(screenHeight - mergeConfirmDialog.getSize().height) / 2);    
            mergeConfirmDialog.setVisible(true);
        }
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelMergeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelMergeButtonActionPerformed
        mergeConfirmDialog.dispose();        
    }//GEN-LAST:event_cancelMergeButtonActionPerformed

    private void confirmMergeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmMergeButtonActionPerformed
        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
	int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
	confirmDialog.setSize(285, 190);
        confirmDialog.setLocation((screenWidth - confirmDialog.getSize().width) / 2,(screenHeight - confirmDialog.getSize().height) / 2);        
        confirmInfoLabel.setText("Merger complete.");
        confirmDialog.setVisible(true);
        mergeConfirmDialog.dispose();
    }//GEN-LAST:event_confirmMergeButtonActionPerformed

    private void confirmDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmDialogButtonActionPerformed
        // TODO add your handling code here:
        UserList userList = new UserList();
        userList.UserListVisible();
        confirmDialog.dispose();
	this.setVisible(false); 
    }//GEN-LAST:event_confirmDialogButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelMergeButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JDialog confirmDialog;
    private javax.swing.JButton confirmDialogButton;
    private javax.swing.JLabel confirmInfoLabel;
    private javax.swing.JButton confirmMergeButton;
    private javax.swing.JPanel confirmPanel;
    private javax.swing.JPanel docSignin;
    private javax.swing.JLabel firstAccountLabel;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JDialog jDialog5;
    private javax.swing.JDialog jDialog6;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog mergeConfirmDialog;
    private javax.swing.JLabel mergeConfirmLabel1;
    private javax.swing.JLabel mergeConfirmLabel2;
    private javax.swing.JLabel reminderLabel;
    private javax.swing.JTable secondAccountTable;
    // End of variables declaration//GEN-END:variables
}
