

package GUI;
import java.awt.*;
/**
 *
 * @author shaosh
 */
public class DoctorMain extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    private final int DOCTOR = 1;
    private final int PATIENT = 2;
    public DoctorMain() {
        initComponents();
        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
	int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
	this.setLocation((screenWidth - this.getSize().width) / 2,(screenHeight - this.getSize().height) / 2); 
    }
    public void DoctorMainVisible(){
        this.setVisible(true);		
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        findButton = new javax.swing.JButton();
        typeLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        changeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doctor Home");
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(270, 400));
        setResizable(false);

        panel.setLayout(null);

        createButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        createButton.setText("Create Patient");
        createButton.setPreferredSize(new java.awt.Dimension(100, 30));
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        panel.add(createButton);
        createButton.setBounds(50, 80, 170, 40);

        nameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        nameLabel.setText("DoctorName");
        panel.add(nameLabel);
        nameLabel.setBounds(100, 30, 90, 18);

        findButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        findButton.setText("Find");
        findButton.setPreferredSize(new java.awt.Dimension(100, 30));
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });
        panel.add(findButton);
        findButton.setBounds(50, 150, 170, 40);

        typeLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        typeLabel.setText("Doctor:");
        panel.add(typeLabel);
        typeLabel.setBounds(50, 30, 50, 18);

        exitButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        exitButton.setText("Exit");
        exitButton.setPreferredSize(new java.awt.Dimension(100, 30));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        panel.add(exitButton);
        exitButton.setBounds(50, 290, 170, 40);

        changeButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        changeButton.setText("Change User");
        changeButton.setPreferredSize(new java.awt.Dimension(100, 30));
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });
        panel.add(changeButton);
        changeButton.setBounds(50, 220, 170, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Doctor Main");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        CreateUser createUser = new CreateUser(PATIENT);
        createUser.CreateUserVisible();
        this.dispose();
    }//GEN-LAST:event_createButtonActionPerformed

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
        // TODO add your handling code here:
        Find find = new Find(DOCTOR);
        find.FindVisible();
        this.dispose();
    }//GEN-LAST:event_findButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        // TODO add your handling code here:
        SignIn signIn = new SignIn();
        signIn.SignInVisible();
        this.dispose();
    }//GEN-LAST:event_changeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeButton;
    private javax.swing.JButton createButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton findButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
