

package GUI;
import java.awt.*;
/**
 *
 * @author shaosh
 */
public class PatientMain extends javax.swing.JFrame {
    private final int PATIENT = 2;
    private final int DOCTORVIEW = 0;
    private final int DOCTORCREATE = 1;
    private final int PATIENTVIEW = 2;
    private final int PATIENTUPDATE = 3;
    /**
     * Creates new form Welcome
     */
    public PatientMain() {
        initComponents();
        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
	int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
	this.setLocation((screenWidth - this.getSize().width) / 2,(screenHeight - this.getSize().height) / 2); 
    }
    public void PatientMainVisible(){
        this.setVisible(true);		
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        historyButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        changeButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Patient Home");
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(270, 400));
        setResizable(false);

        panel.setLayout(null);

        historyButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        historyButton.setText("View History");
        historyButton.setPreferredSize(new java.awt.Dimension(100, 30));
        historyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButtonActionPerformed(evt);
            }
        });
        panel.add(historyButton);
        historyButton.setBounds(50, 80, 170, 40);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setText("PatientName");
        panel.add(jLabel1);
        jLabel1.setBounds(100, 30, 90, 18);

        updateButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        updateButton.setText("Update Information");
        updateButton.setPreferredSize(new java.awt.Dimension(100, 30));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        panel.add(updateButton);
        updateButton.setBounds(50, 150, 170, 40);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("Patient:");
        panel.add(jLabel2);
        jLabel2.setBounds(50, 30, 90, 18);

        changeButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        changeButton.setText("Change User");
        changeButton.setPreferredSize(new java.awt.Dimension(100, 30));
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });
        panel.add(changeButton);
        changeButton.setBounds(50, 220, 170, 40);

        exitButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        exitButton.setText("Exit");
        exitButton.setPreferredSize(new java.awt.Dimension(100, 30));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        panel.add(exitButton);
        exitButton.setBounds(50, 290, 170, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Patient Main");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
        HistoryList history = new HistoryList(PATIENT);
        history.HistoryVisible();
        this.dispose();      
    }//GEN-LAST:event_historyButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        PatientInfo patientInfo = new PatientInfo(PATIENTUPDATE);        
        patientInfo.patientAccessReadOnly();
        patientInfo.PatientInfoVisible();
        this.dispose();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        // TODO add your handling code here:
        SignIn signIn = new SignIn();
        signIn.SignInVisible();
        this.dispose();
    }//GEN-LAST:event_changeButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton historyButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel panel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
