
package GUI;

import java.awt.*;
import javax.swing.*;
import java.util.*;
/**
 *
 * @author shaosh
 */
public class Find extends javax.swing.JFrame {

    /**
     * Creates new form DocSignIn
     */
    private final int ADMIN = 0;
    private final int DOCTOR = 1;
    private final int NURSE = 3;
    private final int MERGE = 4;
    private final int ASSIGN = 5;
    private int type = -1;
    public Find(int type) {
        initComponents();
        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
	int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
	this.setLocation((screenWidth - this.getSize().width) / 2,(screenHeight - this.getSize().height) / 2); 
        //Set JComboBoxes
        Calendar cal = Calendar.getInstance();
        this.type = type;
//        yearCombo.setMaximumRowCount(10);
//        monthCombo.setMaximumRowCount(10);
//        dayCombo.setMaximumRowCount(10);
        yearCombo.addItem(" ");
        monthCombo.addItem(" ");
        dayCombo.addItem(" ");        
        for(int i = 1900; i <= cal.get(Calendar.YEAR); i++)
            yearCombo.addItem(i);	       
        String months[] = {"Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"};
        for(int i = 0; i < 12; i++)
            monthCombo.addItem(months[i]);
        for(int i = 1; i <= 31; i++)
            dayCombo.addItem(i);
        radioGroup.add(maleRadio);
	radioGroup.add(femaleRadio);
        if(this.type == MERGE){
            reminderLabel.setText("Find the second user to merge");
        }
        else if(this.type == ASSIGN)
            reminderLabel.setText("Find the doctor to assign to");
    }
    public void FindVisible(){
            this.setVisible(true);		
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGroup = new javax.swing.ButtonGroup();
        jDialog2 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        firstLabel = new javax.swing.JLabel();
        lastLabel = new javax.swing.JLabel();
        findButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        lastField = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        monthCombo = new javax.swing.JComboBox();
        dayCombo = new javax.swing.JComboBox();
        yearCombo = new javax.swing.JComboBox();
        birthLabel = new javax.swing.JLabel();
        maleRadio = new javax.swing.JRadioButton();
        femaleRadio = new javax.swing.JRadioButton();
        firstField = new javax.swing.JTextField();
        reminderLabel = new javax.swing.JLabel();

        jDialog2.setTitle("Attention");
        jDialog2.setIconImage(null);
        jDialog2.setResizable(false);
        jDialog2.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel1.setText("Do you still want to continue?");
        jDialog2.getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 60, 290, 30);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("Patients with the same profile have already existed.");
        jDialog2.getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 30, 290, 30);

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton1.setText("Confirm");
        jDialog2.getContentPane().add(jButton1);
        jButton1.setBounds(80, 110, 100, 30);

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton2.setText("Cancel");
        jDialog2.getContentPane().add(jButton2);
        jButton2.setBounds(270, 110, 100, 30);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Find");
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(450, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        panel.setMaximumSize(new java.awt.Dimension(450, 300));
        panel.setMinimumSize(new java.awt.Dimension(0, 0));
        panel.setPreferredSize(new java.awt.Dimension(450, 300));
        panel.setLayout(null);

        firstLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        firstLabel.setText("First Name");
        panel.add(firstLabel);
        firstLabel.setBounds(70, 40, 100, 30);

        lastLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lastLabel.setText("Last Name");
        panel.add(lastLabel);
        lastLabel.setBounds(70, 90, 100, 30);

        findButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        findButton.setText("Find");
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });
        panel.add(findButton);
        findButton.setBounds(70, 220, 100, 30);

        cancelButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        panel.add(cancelButton);
        cancelButton.setBounds(280, 220, 100, 30);

        lastField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        panel.add(lastField);
        lastField.setBounds(180, 90, 200, 30);

        genderLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        genderLabel.setText("Gender");
        panel.add(genderLabel);
        genderLabel.setBounds(70, 180, 100, 30);

        monthCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        monthCombo.setMaximumRowCount(10);
        panel.add(monthCombo);
        monthCombo.setBounds(180, 140, 60, 30);

        dayCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        dayCombo.setMaximumRowCount(10);
        panel.add(dayCombo);
        dayCombo.setBounds(250, 140, 50, 30);

        yearCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        yearCombo.setMaximumRowCount(10);
        yearCombo.setToolTipText("");
        yearCombo.setAutoscrolls(true);
        yearCombo.setPreferredSize(new java.awt.Dimension(70, 30));
        panel.add(yearCombo);
        yearCombo.setBounds(310, 140, 70, 30);

        birthLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        birthLabel.setText("Birthday");
        panel.add(birthLabel);
        birthLabel.setBounds(70, 140, 100, 30);

        maleRadio.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        maleRadio.setText("Male");
        panel.add(maleRadio);
        maleRadio.setBounds(180, 180, 51, 30);

        femaleRadio.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        femaleRadio.setText("Female");
        panel.add(femaleRadio);
        femaleRadio.setBounds(280, 180, 100, 30);

        firstField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        panel.add(firstField);
        firstField.setBounds(180, 40, 200, 30);

        reminderLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        panel.add(reminderLabel);
        reminderLabel.setBounds(70, 10, 310, 20);

        getContentPane().add(panel);
        panel.setBounds(0, 0, 450, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if(this.type == ADMIN || this.type == MERGE || this.type == ASSIGN){
            AdminMain adminMain = new AdminMain();
            adminMain.AdminMainVisible();
            this.dispose();
        }
        else if(this.type == DOCTOR){ 
            DoctorMain doctorMain = new DoctorMain();
            doctorMain.DoctorMainVisible();
            this.dispose();
        }
        else if(this.type == NURSE){ 
            NurseMain nurseMain = new NurseMain();
            nurseMain.NurseMainVisible();
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid user type!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
        this.dispose();
//	this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
    //*******************************
    //need coding
    //*******************************	
    	//Check if the information are correctly entered
        if(lastField.getText().length() == 0 || firstField.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Please enter the names!", "ERROR", JOptionPane.INFORMATION_MESSAGE);					
        }
        else if(maleRadio.isSelected() == false && femaleRadio.isSelected() == false){
            JOptionPane.showMessageDialog(null, "Please select the gender!", "ERROR", JOptionPane.INFORMATION_MESSAGE);	
        }
        else if((monthCombo.getSelectedIndex() == 4 || monthCombo.getSelectedIndex() == 6 || 
        monthCombo.getSelectedIndex() == 9 || monthCombo.getSelectedIndex() == 11) &&
        dayCombo.getSelectedIndex() > 30){
            JOptionPane.showMessageDialog(null, "Date is wrong!", "ERROR", JOptionPane.INFORMATION_MESSAGE);	
        }
        else if((monthCombo.getSelectedIndex() == 2 && ((int)(yearCombo.getSelectedItem()) % 4 == 0 &&
        ((int)yearCombo.getSelectedItem()) % 100 == 0 && ((int)yearCombo.getSelectedItem()) % 400 == 0)) &&
        dayCombo.getSelectedIndex() > 29){
            JOptionPane.showMessageDialog(null, "Date is wrong!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
        else if((monthCombo.getSelectedIndex() == 2 && ((int)(yearCombo.getSelectedItem()) % 4 == 0 &&
        ((int)yearCombo.getSelectedItem()) % 100 != 0)) &&
        dayCombo.getSelectedIndex() > 29){
            JOptionPane.showMessageDialog(null, "Date is wrong!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
        else if((monthCombo.getSelectedIndex() == 2 && ((int)(yearCombo.getSelectedItem()) % 4 != 0 ||
        (((int)yearCombo.getSelectedItem()) % 100 == 0 && ((int)yearCombo.getSelectedItem()) % 400 != 0))) &&
        dayCombo.getSelectedIndex() > 28){
            JOptionPane.showMessageDialog(null, "Date is wrong!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(monthCombo.getSelectedIndex() == 0 || dayCombo.getSelectedIndex() == 0 || yearCombo.getSelectedIndex() == 0 ){
            JOptionPane.showMessageDialog(null, "Please enter birth date!", "ERROR", JOptionPane.INFORMATION_MESSAGE);	
        }								
        //*******************************
        //need coding
        //*******************************
        //Search for info
        //Use dialog to show if search is success
        else if(this.type == DOCTOR){
            PatientList patientList = new PatientList(DOCTOR);
            patientList.PatientListVisible();
            this.dispose();
        } 
        else if(this.type == NURSE){
            PatientList patientList = new PatientList(NURSE);
            patientList.PatientListVisible();
            this.dispose();
        }
        else if(this.type == ADMIN){
            UserList userList = new UserList();
            userList.UserListVisible();
            this.dispose();
        }
        else if(this.type == MERGE){
            ConfirmSecond confirmSecond = new ConfirmSecond(MERGE);
            confirmSecond.ConfirmSecondVisible();
            this.dispose();
        }
        else if(this.type == ASSIGN){
            ConfirmSecond confirmSecond = new ConfirmSecond(ASSIGN);
            confirmSecond.ConfirmSecondVisible();
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Unknown error!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }           
    }//GEN-LAST:event_findButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel birthLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox dayCombo;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JButton findButton;
    private javax.swing.JTextField firstField;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField lastField;
    private javax.swing.JLabel lastLabel;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JComboBox monthCombo;
    private javax.swing.JPanel panel;
    private javax.swing.ButtonGroup radioGroup;
    private javax.swing.JLabel reminderLabel;
    private javax.swing.JComboBox yearCombo;
    // End of variables declaration//GEN-END:variables
}
