/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Toolkit;
import java.util.*;
import java.text.*;
import javax.swing.JOptionPane;

/**
 *
 * @author shaosh
 */
public class PatientInfo extends javax.swing.JFrame {
    private SimpleDateFormat sdf = new SimpleDateFormat("MM-dd-yyyy HH:mm:ss");
    private int type = -1;
    private final int DOCTORVIEW = 0;
    private final int DOCTORCREATE = 1;
    private final int PATIENTVIEW = 2;
    private final int PATIENTUPDATE = 3;    
    private final int NURSECREATE = 4;
    private final int DOCTOR = 1;
    private final int PATIENT = 2;
    private int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
    private int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
    /**
     * Creates new form PatientInfo
     */
    public PatientInfo(int type) {
        initComponents();
//        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
//	int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
	this.setLocation((screenWidth - this.getSize().width) / 2,(screenHeight - this.getSize().height) / 2); 

        this.type = type;
        Timer timer = new Timer();
        timer.schedule(new ShowTime(), new Date(), 1000);
    }
    
    class ShowTime extends TimerTask{
        public void run(){
            datetime.setText(sdf.format(new Date()));
            repaint();
        }
    }
    
    public void PatientInfoVisible(){
        this.setVisible(true);		
    }
    
    public void viewRecordReadOnly(int type){
        addrField.setEditable(false);
        contactField.setEditable(false);
        heightField.setEditable(false);
        weightField.setEditable(false);
        bloodField.setEditable(false);
        insurField.setEditable(false);
        allergyArea.setEditable(false);
        mediArea.setEditable(false);
        confirmButton.setEnabled(false);
        tempField.setEditable(false);
        pressureField.setEditable(false);
        sugarField.setEditable(false);
        weightField2.setEditable(false);
        complainArea.setEditable(false);
        observeArea.setEditable(false);
        prescriptArea.setEditable(false);
        setPermissionButton.setEnabled(false);
        if(type == PATIENTVIEW)
            markInvalidButton.setEnabled(false);
        confirmButton2.setEnabled(false);
    }
    
    public void patientAccessReadOnly(){
        addrField.setEditable(false);
        contactField.setEditable(false);
        heightField.setEditable(false);
        weightField.setEditable(false);
        bloodField.setEditable(false);
        insurField.setEditable(false);
        allergyArea.setEditable(false);
        mediArea.setEditable(false);
        confirmButton.setEnabled(false);
        complainArea.setEditable(false);
        observeArea.setEditable(false);
        prescriptArea.setEditable(false);
        setPermissionButton.setEnabled(false);
        markInvalidButton.setEnabled(false);
    }
    
    public void nurseAccessReadOnly(){
        complainArea.setEditable(false);
        observeArea.setEditable(false);
        prescriptArea.setEditable(false);
        setPermissionButton.setEnabled(false);
        markInvalidButton.setEnabled(false);
        prevButton.setEnabled(false);
        backButton.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        completeDialog = new javax.swing.JDialog();
        completePanel = new javax.swing.JPanel();
        completeButton = new javax.swing.JButton();
        completeLabel = new javax.swing.JLabel();
        setPermissionDialog = new javax.swing.JDialog();
        setPermissionPanel = new javax.swing.JPanel();
        patientLabel2 = new javax.swing.JLabel();
        patientName = new javax.swing.JLabel();
        doctorLabel2 = new javax.swing.JLabel();
        doctorName = new javax.swing.JLabel();
        tempCheck = new javax.swing.JCheckBox();
        bloodCheck = new javax.swing.JCheckBox();
        sugarCheck = new javax.swing.JCheckBox();
        weightCheck = new javax.swing.JCheckBox();
        cancelButton3 = new javax.swing.JButton();
        cancelPermissionButton = new javax.swing.JButton();
        grantButton = new javax.swing.JButton();
        tabbedPane = new javax.swing.JTabbedPane();
        basicPanel = new javax.swing.JPanel();
        lastLabel = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        firstLabel = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        birthLabel = new javax.swing.JLabel();
        birth = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        addrLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        contactField = new javax.swing.JTextField();
        addrField = new javax.swing.JTextField();
        heightLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();
        bloodLabel = new javax.swing.JLabel();
        heightField = new javax.swing.JTextField();
        bloodField = new javax.swing.JTextField();
        insurLabel = new javax.swing.JLabel();
        insurField = new javax.swing.JTextField();
        allergyLabel = new javax.swing.JLabel();
        mediLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        allergyArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        mediArea = new javax.swing.JTextArea();
        confirmButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        weightField = new javax.swing.JTextField();
        healthPanel = new javax.swing.JPanel();
        visitLabel = new javax.swing.JLabel();
        visitDate = new javax.swing.JLabel();
        tempLabel = new javax.swing.JLabel();
        pressureLabel = new javax.swing.JLabel();
        pressureField = new javax.swing.JTextField();
        sugarLabel = new javax.swing.JLabel();
        tempField = new javax.swing.JTextField();
        weightLabel2 = new javax.swing.JLabel();
        weightField2 = new javax.swing.JTextField();
        complainLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        complainArea = new javax.swing.JTextArea();
        observeLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        observeArea = new javax.swing.JTextArea();
        prescriptLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        prescriptArea = new javax.swing.JTextArea();
        prevButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        markInvalidButton = new javax.swing.JButton();
        confirmButton2 = new javax.swing.JButton();
        cancelButton2 = new javax.swing.JButton();
        sugarField = new javax.swing.JTextField();
        setPermissionButton = new javax.swing.JButton();
        patientLabel = new javax.swing.JLabel();
        patientname = new javax.swing.JLabel();
        datetime = new javax.swing.JLabel();

        completeDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        completeDialog.setTitle("Attention");
        completeDialog.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        completeDialog.setIconImage(null);
        completeDialog.setName("completeDialog"); // NOI18N
        completeDialog.getContentPane().setLayout(null);

        completePanel.setMaximumSize(new java.awt.Dimension(285, 190));
        completePanel.setPreferredSize(new java.awt.Dimension(285, 190));
        completePanel.setLayout(null);

        completeButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        completeButton.setText("Confirm");
        completeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeButtonActionPerformed(evt);
            }
        });
        completePanel.add(completeButton);
        completeButton.setBounds(90, 100, 100, 30);

        completeLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        completePanel.add(completeLabel);
        completeLabel.setBounds(60, 40, 160, 30);

        completeDialog.getContentPane().add(completePanel);
        completePanel.setBounds(0, 0, 285, 190);

        setPermissionDialog.setTitle("Set Permission");
        setPermissionDialog.getContentPane().setLayout(null);

        setPermissionPanel.setLayout(null);

        patientLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        patientLabel2.setText("Patient:");
        setPermissionPanel.add(patientLabel2);
        patientLabel2.setBounds(60, 30, 50, 18);

        patientName.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        patientName.setText("PatientName");
        setPermissionPanel.add(patientName);
        patientName.setBounds(120, 30, 80, 18);

        doctorLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        doctorLabel2.setText("Doctor:");
        setPermissionPanel.add(doctorLabel2);
        doctorLabel2.setBounds(260, 30, 50, 18);

        doctorName.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        doctorName.setText("DoctorName");
        setPermissionPanel.add(doctorName);
        doctorName.setBounds(310, 30, 70, 18);

        tempCheck.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tempCheck.setText("Temperature");
        setPermissionPanel.add(tempCheck);
        tempCheck.setBounds(60, 70, 110, 27);

        bloodCheck.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        bloodCheck.setText("Blood Pressure");
        setPermissionPanel.add(bloodCheck);
        bloodCheck.setBounds(260, 70, 120, 27);

        sugarCheck.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        sugarCheck.setText("Sugar Level");
        setPermissionPanel.add(sugarCheck);
        sugarCheck.setBounds(60, 110, 110, 27);

        weightCheck.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        weightCheck.setText("Weight");
        setPermissionPanel.add(weightCheck);
        weightCheck.setBounds(260, 110, 70, 27);

        cancelButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cancelButton3.setText("Cancel");
        cancelButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton3ActionPerformed(evt);
            }
        });
        setPermissionPanel.add(cancelButton3);
        cancelButton3.setBounds(60, 210, 130, 30);

        cancelPermissionButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cancelPermissionButton.setText("Cancel Permission");
        cancelPermissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPermissionButtonActionPerformed(evt);
            }
        });
        setPermissionPanel.add(cancelPermissionButton);
        cancelPermissionButton.setBounds(260, 160, 130, 30);

        grantButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        grantButton.setText("Grant Permission");
        grantButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grantButtonActionPerformed(evt);
            }
        });
        setPermissionPanel.add(grantButton);
        grantButton.setBounds(60, 160, 130, 30);

        setPermissionDialog.getContentPane().add(setPermissionPanel);
        setPermissionPanel.setBounds(0, 0, 400, 300);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Visit Record");
        setPreferredSize(new java.awt.Dimension(450, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        basicPanel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        basicPanel.setLayout(null);

        lastLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lastLabel.setText("Last Name");
        basicPanel.add(lastLabel);
        lastLabel.setBounds(20, 10, 75, 20);

        lastname.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lastname.setText("lastname");
        basicPanel.add(lastname);
        lastname.setBounds(95, 10, 100, 20);

        firstLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        firstLabel.setText("First Name ");
        basicPanel.add(firstLabel);
        firstLabel.setBounds(210, 10, 75, 20);

        firstname.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        firstname.setText("firstname");
        basicPanel.add(firstname);
        firstname.setBounds(290, 10, 100, 20);

        birthLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        birthLabel.setText("Birth");
        basicPanel.add(birthLabel);
        birthLabel.setBounds(20, 50, 50, 20);

        birth.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        birth.setText("MM-DD-YYYY");
        basicPanel.add(birth);
        birth.setBounds(70, 50, 100, 20);

        genderLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        genderLabel.setText("Gender ");
        basicPanel.add(genderLabel);
        genderLabel.setBounds(210, 50, 50, 20);

        gender.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        gender.setText("Male/Female");
        basicPanel.add(gender);
        gender.setBounds(260, 50, 80, 20);

        addrLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        addrLabel.setText("Address");
        basicPanel.add(addrLabel);
        addrLabel.setBounds(20, 95, 75, 20);

        contactLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        contactLabel.setText("Contact");
        basicPanel.add(contactLabel);
        contactLabel.setBounds(230, 95, 75, 20);

        contactField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        basicPanel.add(contactField);
        contactField.setBounds(280, 90, 130, 30);

        addrField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        basicPanel.add(addrField);
        addrField.setBounds(70, 90, 140, 30);

        heightLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        heightLabel.setText("Height(cm)");
        basicPanel.add(heightLabel);
        heightLabel.setBounds(20, 155, 75, 20);

        weightLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        weightLabel.setText("Weight(kg)");
        basicPanel.add(weightLabel);
        weightLabel.setBounds(160, 155, 75, 20);

        bloodLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        bloodLabel.setText("Blood Type");
        basicPanel.add(bloodLabel);
        bloodLabel.setBounds(300, 155, 75, 20);

        heightField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        basicPanel.add(heightField);
        heightField.setBounds(90, 150, 45, 30);

        bloodField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        basicPanel.add(bloodField);
        bloodField.setBounds(370, 150, 40, 30);

        insurLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        insurLabel.setText("Insurance");
        basicPanel.add(insurLabel);
        insurLabel.setBounds(20, 215, 75, 20);

        insurField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        basicPanel.add(insurField);
        insurField.setBounds(90, 210, 180, 30);

        allergyLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        allergyLabel.setText("Allergy");
        basicPanel.add(allergyLabel);
        allergyLabel.setBounds(20, 270, 75, 20);

        mediLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        mediLabel.setText("Medication");
        basicPanel.add(mediLabel);
        mediLabel.setBounds(20, 380, 75, 20);

        allergyArea.setColumns(20);
        allergyArea.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        allergyArea.setRows(5);
        jScrollPane1.setViewportView(allergyArea);

        basicPanel.add(jScrollPane1);
        jScrollPane1.setBounds(90, 270, 320, 80);

        mediArea.setColumns(20);
        mediArea.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        mediArea.setRows(5);
        jScrollPane2.setViewportView(mediArea);

        basicPanel.add(jScrollPane2);
        jScrollPane2.setBounds(90, 380, 320, 80);

        confirmButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        basicPanel.add(confirmButton);
        confirmButton.setBounds(190, 500, 100, 30);

        cancelButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        basicPanel.add(cancelButton);
        cancelButton.setBounds(310, 500, 100, 30);

        weightField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        basicPanel.add(weightField);
        weightField.setBounds(230, 150, 45, 30);

        tabbedPane.addTab("Basic", basicPanel);

        healthPanel.setLayout(null);

        visitLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        visitLabel.setText("Visit Date");
        healthPanel.add(visitLabel);
        visitLabel.setBounds(20, 10, 70, 20);

        visitDate.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        visitDate.setText("MM-DD-YYYY");
        healthPanel.add(visitDate);
        visitDate.setBounds(90, 10, 90, 18);

        tempLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        tempLabel.setText("Temperature(C)");
        healthPanel.add(tempLabel);
        tempLabel.setBounds(190, 10, 85, 18);

        pressureLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        pressureLabel.setText("Blood Pressure(mmHg)");
        healthPanel.add(pressureLabel);
        pressureLabel.setBounds(20, 50, 121, 20);

        pressureField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        healthPanel.add(pressureField);
        pressureField.setBounds(150, 45, 45, 30);

        sugarLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        sugarLabel.setText("Sugar(mg/dL)");
        healthPanel.add(sugarLabel);
        sugarLabel.setBounds(200, 50, 73, 20);

        tempField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        healthPanel.add(tempField);
        tempField.setBounds(280, 5, 30, 30);

        weightLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        weightLabel2.setText("Weight(kg)");
        healthPanel.add(weightLabel2);
        weightLabel2.setBounds(320, 50, 60, 20);

        weightField2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        healthPanel.add(weightField2);
        weightField2.setBounds(390, 45, 30, 30);

        complainLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        complainLabel.setText("Complain");
        healthPanel.add(complainLabel);
        complainLabel.setBounds(20, 85, 70, 20);

        complainArea.setColumns(20);
        complainArea.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        complainArea.setRows(5);
        jScrollPane3.setViewportView(complainArea);

        healthPanel.add(jScrollPane3);
        jScrollPane3.setBounds(110, 90, 310, 100);

        observeLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        observeLabel.setText("Observation");
        healthPanel.add(observeLabel);
        observeLabel.setBounds(20, 205, 70, 20);

        observeArea.setColumns(20);
        observeArea.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        observeArea.setRows(5);
        jScrollPane4.setViewportView(observeArea);

        healthPanel.add(jScrollPane4);
        jScrollPane4.setBounds(110, 210, 310, 100);

        prescriptLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        prescriptLabel.setText("Prescription");
        healthPanel.add(prescriptLabel);
        prescriptLabel.setBounds(20, 325, 70, 20);

        prescriptArea.setColumns(20);
        prescriptArea.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        prescriptArea.setRows(5);
        jScrollPane5.setViewportView(prescriptArea);

        healthPanel.add(jScrollPane5);
        jScrollPane5.setBounds(110, 330, 310, 100);

        prevButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        prevButton.setText("<< Previous");
        healthPanel.add(prevButton);
        prevButton.setBounds(20, 450, 100, 30);

        backButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        backButton.setText("Back >>");
        healthPanel.add(backButton);
        backButton.setBounds(20, 500, 100, 30);

        markInvalidButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        markInvalidButton.setText("Mark Invalid");
        markInvalidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markInvalidButtonActionPerformed(evt);
            }
        });
        healthPanel.add(markInvalidButton);
        markInvalidButton.setBounds(300, 450, 120, 30);

        confirmButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        confirmButton2.setText("Confirm");
        confirmButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButton2ActionPerformed(evt);
            }
        });
        healthPanel.add(confirmButton2);
        confirmButton2.setBounds(160, 500, 120, 30);

        cancelButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cancelButton2.setText("Cancel");
        cancelButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton2ActionPerformed(evt);
            }
        });
        healthPanel.add(cancelButton2);
        cancelButton2.setBounds(300, 500, 120, 30);

        sugarField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        healthPanel.add(sugarField);
        sugarField.setBounds(280, 45, 30, 30);

        setPermissionButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        setPermissionButton.setText("Set Permission");
        setPermissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPermissionButtonActionPerformed(evt);
            }
        });
        healthPanel.add(setPermissionButton);
        setPermissionButton.setBounds(160, 450, 120, 30);

        tabbedPane.addTab("Health", healthPanel);

        getContentPane().add(tabbedPane);
        tabbedPane.setBounds(0, 30, 450, 620);

        patientLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        patientLabel.setText("Patient:");
        getContentPane().add(patientLabel);
        patientLabel.setBounds(90, 10, 50, 18);

        patientname.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        patientname.setText("PatientName");
        getContentPane().add(patientname);
        patientname.setBounds(140, 10, 100, 18);

        datetime.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        datetime.setText("MM-DD-YYYY HH:MM:SS");
        getContentPane().add(datetime);
        datetime.setBounds(240, 10, 160, 18);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
//        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
//        int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        completeDialog.setSize(285, 190);
        completeDialog.setLocation((screenWidth - completeDialog.getSize().width) / 2,(screenHeight - completeDialog.getSize().height) / 2);            
        completeLabel.setText("Database update complete.");
        completeDialog.setVisible(true);
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void completeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeButtonActionPerformed
        completeDialog.dispose();
    }//GEN-LAST:event_completeButtonActionPerformed

    private void confirmButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButton2ActionPerformed
//        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
//        int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        completeDialog.setSize(285, 190);
        completeDialog.setLocation((screenWidth - completeDialog.getSize().width) / 2,(screenHeight - completeDialog.getSize().height) / 2);            
        completeLabel.setText("Database update complete.");
        completeDialog.setVisible(true);
    }//GEN-LAST:event_confirmButton2ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if(type == DOCTORVIEW){
            HistoryList historyList = new HistoryList(DOCTOR);
            historyList.HistoryVisible();
            this.dispose();
        }
        else if(type == DOCTORCREATE){
            DoctorMain doctorMain = new DoctorMain();
            doctorMain.DoctorMainVisible();
            this.dispose();
        }
        else if(type == PATIENTVIEW){
            HistoryList historyList = new HistoryList(PATIENT);
            historyList.HistoryVisible();
            this.dispose();
        }
        else if(type == PATIENTUPDATE){
            PatientMain patientMain = new PatientMain();
            patientMain.PatientMainVisible();
            this.dispose();
        }
        else if(type == NURSECREATE){
            NurseMain nurseMain = new NurseMain();
            nurseMain.NurseMainVisible();
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid type!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void cancelButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton2ActionPerformed
        if(type == DOCTORVIEW){
            HistoryList historyList = new HistoryList(DOCTOR);
            historyList.HistoryVisible();
            this.dispose();
        }
        else if(type == DOCTORCREATE){
            DoctorMain doctorMain = new DoctorMain();
            doctorMain.DoctorMainVisible();
            this.dispose();
        }
        else if(type == PATIENTVIEW){
            HistoryList historyList = new HistoryList(PATIENT);
            historyList.HistoryVisible();
            this.dispose();
        }
        else if(type == PATIENTUPDATE){
            PatientMain patientMain = new PatientMain();
            patientMain.PatientMainVisible();
            this.dispose();
        }
        else if(type == NURSECREATE){
            NurseMain nurseMain = new NurseMain();
            nurseMain.NurseMainVisible();
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid type!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cancelButton2ActionPerformed

    private void grantButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grantButtonActionPerformed
        if(tempCheck.isSelected()||bloodCheck.isSelected()||sugarCheck.isSelected()||weightCheck.isSelected()){
            completeDialog.setSize(285, 190);
            completeDialog.setLocation((screenWidth - completeDialog.getSize().width) / 2,(screenHeight - completeDialog.getSize().height) / 2);            
            completeLabel.setText("Permission is granted.");
            completeDialog.setVisible(true);
            setPermissionDialog.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please check at least one indicator!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_grantButtonActionPerformed

    private void cancelButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton3ActionPerformed
        setPermissionDialog.dispose();
    }//GEN-LAST:event_cancelButton3ActionPerformed

    private void cancelPermissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPermissionButtonActionPerformed
        if(tempCheck.isSelected()||bloodCheck.isSelected()||sugarCheck.isSelected()||weightCheck.isSelected()){
            completeDialog.setSize(285, 190);
            completeDialog.setLocation((screenWidth - completeDialog.getSize().width) / 2,(screenHeight - completeDialog.getSize().height) / 2);            
            completeLabel.setText("Permission is canceled.");
            completeDialog.setVisible(true);
            setPermissionDialog.setVisible(false);
        }
        //need to consider if the checked permission exists.
        else{
            JOptionPane.showMessageDialog(null, "Please check at least one indicator!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cancelPermissionButtonActionPerformed

    private void markInvalidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markInvalidButtonActionPerformed
        completeDialog.setSize(285, 190);
        completeDialog.setLocation((screenWidth - completeDialog.getSize().width) / 2,(screenHeight - completeDialog.getSize().height) / 2);            
        completeLabel.setText("Marking invalid complete.");
        completeDialog.setVisible(true);
    }//GEN-LAST:event_markInvalidButtonActionPerformed

    private void setPermissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPermissionButtonActionPerformed
        setPermissionDialog.setSize(450, 300);
        setPermissionDialog.setLocation((screenWidth - setPermissionDialog.getSize().width) / 2,(screenHeight - setPermissionDialog.getSize().height) / 2);            
        setPermissionDialog.setVisible(true);
    }//GEN-LAST:event_setPermissionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addrField;
    private javax.swing.JLabel addrLabel;
    private javax.swing.JTextArea allergyArea;
    private javax.swing.JLabel allergyLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel basicPanel;
    private javax.swing.JLabel birth;
    private javax.swing.JLabel birthLabel;
    private javax.swing.JCheckBox bloodCheck;
    private javax.swing.JTextField bloodField;
    private javax.swing.JLabel bloodLabel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelButton2;
    private javax.swing.JButton cancelButton3;
    private javax.swing.JButton cancelPermissionButton;
    private javax.swing.JTextArea complainArea;
    private javax.swing.JLabel complainLabel;
    private javax.swing.JButton completeButton;
    private javax.swing.JDialog completeDialog;
    private javax.swing.JLabel completeLabel;
    private javax.swing.JPanel completePanel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton confirmButton2;
    private javax.swing.JTextField contactField;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel datetime;
    private javax.swing.JLabel doctorLabel2;
    private javax.swing.JLabel doctorName;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JButton grantButton;
    private javax.swing.JPanel healthPanel;
    private javax.swing.JTextField heightField;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JTextField insurField;
    private javax.swing.JLabel insurLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lastLabel;
    private javax.swing.JLabel lastname;
    private javax.swing.JButton markInvalidButton;
    private javax.swing.JTextArea mediArea;
    private javax.swing.JLabel mediLabel;
    private javax.swing.JTextArea observeArea;
    private javax.swing.JLabel observeLabel;
    private javax.swing.JLabel patientLabel;
    private javax.swing.JLabel patientLabel2;
    private javax.swing.JLabel patientName;
    private javax.swing.JLabel patientname;
    private javax.swing.JTextArea prescriptArea;
    private javax.swing.JLabel prescriptLabel;
    private javax.swing.JTextField pressureField;
    private javax.swing.JLabel pressureLabel;
    private javax.swing.JButton prevButton;
    private javax.swing.JButton setPermissionButton;
    private javax.swing.JDialog setPermissionDialog;
    private javax.swing.JPanel setPermissionPanel;
    private javax.swing.JCheckBox sugarCheck;
    private javax.swing.JTextField sugarField;
    private javax.swing.JLabel sugarLabel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JCheckBox tempCheck;
    private javax.swing.JTextField tempField;
    private javax.swing.JLabel tempLabel;
    private javax.swing.JLabel visitDate;
    private javax.swing.JLabel visitLabel;
    private javax.swing.JCheckBox weightCheck;
    private javax.swing.JTextField weightField;
    private javax.swing.JTextField weightField2;
    private javax.swing.JLabel weightLabel;
    private javax.swing.JLabel weightLabel2;
    // End of variables declaration//GEN-END:variables
}
