
package GUI;

import java.awt.*;
import javax.swing.*;
/**
 *
 * @author shaosh
 */
public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form DocSignIn
     */
    public SignIn() {
        initComponents();
        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
	int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
	this.setLocation((screenWidth - this.getSize().width) / 2,(screenHeight - this.getSize().height) / 2); 
    }
    public void SignInVisible(){
        this.setVisible(true);		
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signin = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        pwLabel = new javax.swing.JLabel();
        signButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        idField = new javax.swing.JTextField();
        pwField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign In");
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(450, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        signin.setMaximumSize(new java.awt.Dimension(450, 300));
        signin.setMinimumSize(new java.awt.Dimension(0, 0));
        signin.setPreferredSize(new java.awt.Dimension(450, 300));
        signin.setLayout(null);

        idLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        idLabel.setText("ID:");
        signin.add(idLabel);
        idLabel.setBounds(75, 50, 100, 30);

        pwLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        pwLabel.setText("Password:");
        signin.add(pwLabel);
        pwLabel.setBounds(75, 100, 100, 30);

        signButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        signButton.setText("Sign In");
        signButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signButtonActionPerformed(evt);
            }
        });
        signin.add(signButton);
        signButton.setBounds(75, 180, 100, 30);

        cancelButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        signin.add(cancelButton);
        cancelButton.setBounds(275, 180, 100, 30);

        idField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        signin.add(idField);
        idField.setBounds(175, 50, 200, 30);

        pwField.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        signin.add(pwField);
        pwField.setBounds(175, 100, 200, 30);

        getContentPane().add(signin);
        signin.setBounds(0, 0, 450, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        Welcome welcome = new Welcome();
	welcome.WelcomeVisible();
        System.exit(0);
//	this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void signButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signButtonActionPerformed
    //*******************************
    //need coding
    //*******************************	
    	if(idField.getText().equals(String.valueOf(pwField.getPassword()))
	&& idField.getText().length() != 0){
            ChangePassword changePW = new ChangePassword();
            changePW.ChangePasswordVisible();
//            this.setVisible(false);
            this.dispose();
	}
        else if(idField.getText().equalsIgnoreCase("doctor")&& String.valueOf(pwField.getPassword()).length() != 0){
            DoctorMain doctorMain = new DoctorMain();
            doctorMain.DoctorMainVisible();
//            this.setVisible(false);
            this.dispose();
        }
        else if(idField.getText().equalsIgnoreCase("patient")&& String.valueOf(pwField.getPassword()).length() != 0){
            PatientMain patientMain = new PatientMain();
            patientMain.PatientMainVisible();
//            this.setVisible(false);
            this.dispose();
        }
        else if(idField.getText().equalsIgnoreCase("admin")&& String.valueOf(pwField.getPassword()).length() != 0){
            AdminMain adminMain = new AdminMain();
            adminMain.AdminMainVisible();
//            this.setVisible(false);
            this.dispose();
        }
        else if(idField.getText().equalsIgnoreCase("nurse")&& String.valueOf(pwField.getPassword()).length() != 0){
            NurseMain nurseMain = new NurseMain();
            nurseMain.NurseMainVisible();
//            this.setVisible(false);
            this.dispose();
        }
	else if (idField.getText().length() == 0 || pwField.getPassword().length == 0 ){
            JOptionPane.showMessageDialog(null, "Please enter your ID or Password!", "ERROR", JOptionPane.INFORMATION_MESSAGE);					
	}
	//*******************************
	//need coding
	//*******************************	
	else{
//          SearchPatient searchPatient = new SearchPatient();
//          searchPatient.SearchPatientVisible();
//          this.setVisible(false);
	}        // TODO add your handling code here:
    }//GEN-LAST:event_signButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPasswordField pwField;
    private javax.swing.JLabel pwLabel;
    private javax.swing.JButton signButton;
    private javax.swing.JPanel signin;
    // End of variables declaration//GEN-END:variables
}
