
package GUI;

import java.awt.*;
import javax.swing.*;
/**
 *
 * @author shaosh
 */
public class UserList extends javax.swing.JFrame {

    private final int ADMIN = 1;
    private final int MERGE = 4;
    private final int ASSIGN = 5;
    public UserList() {
        initComponents();
        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
	int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
	this.setLocation((screenWidth - this.getSize().width) / 2,(screenHeight - this.getSize().height) / 2); 
    }
    public void UserListVisible(){
        this.setVisible(true);		
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        resetDialog = new javax.swing.JDialog();
        resetLabel2 = new javax.swing.JLabel();
        resetLabel1 = new javax.swing.JLabel();
        confirmResetButton = new javax.swing.JButton();
        cancelResetButton = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jDialog3 = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lockoutDialog = new javax.swing.JDialog();
        lockoutLabel1 = new javax.swing.JLabel();
        lockoutLabel2 = new javax.swing.JLabel();
        confirmLockoutButton = new javax.swing.JButton();
        cancelLockoutButton = new javax.swing.JButton();
        unlockDialog = new javax.swing.JDialog();
        unlockLabel2 = new javax.swing.JLabel();
        unlockLabel1 = new javax.swing.JLabel();
        confirmUnlockButton = new javax.swing.JButton();
        cancelUnlockButton = new javax.swing.JButton();
        confirmDialog = new javax.swing.JDialog();
        confirmPanel = new javax.swing.JPanel();
        confirmDialogButton = new javax.swing.JButton();
        confirmInfoLabel = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        lockoutButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        unlockButton = new javax.swing.JButton();
        mergeButton = new javax.swing.JButton();
        assignButton = new javax.swing.JButton();

        resetDialog.setTitle("Attention");
        resetDialog.setIconImage(null);
        resetDialog.setResizable(false);
        resetDialog.getContentPane().setLayout(null);

        resetLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        resetLabel2.setText("Do you still want to continue?");
        resetDialog.getContentPane().add(resetLabel2);
        resetLabel2.setBounds(80, 60, 290, 30);

        resetLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        resetLabel1.setText("The user's password will be reset. ");
        resetDialog.getContentPane().add(resetLabel1);
        resetLabel1.setBounds(80, 30, 220, 30);

        confirmResetButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        confirmResetButton.setText("Confirm");
        confirmResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmResetButtonActionPerformed(evt);
            }
        });
        resetDialog.getContentPane().add(confirmResetButton);
        confirmResetButton.setBounds(80, 110, 100, 30);

        cancelResetButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cancelResetButton.setText("Cancel");
        cancelResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelResetButtonActionPerformed(evt);
            }
        });
        resetDialog.getContentPane().add(cancelResetButton);
        cancelResetButton.setBounds(270, 110, 100, 30);

        idLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        idLabel.setText("Result");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Name    UserID" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jDialog3.setTitle("Attention");
        jDialog3.setIconImage(null);
        jDialog3.setResizable(false);
        jDialog3.getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel4.setText("No such user.");
        jDialog3.getContentPane().add(jLabel4);
        jLabel4.setBounds(55, 30, 90, 30);

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jButton3.setText("Confirm");
        jDialog3.getContentPane().add(jButton3);
        jButton3.setBounds(50, 80, 100, 30);

        lockoutDialog.setTitle("Attention");
        lockoutDialog.setIconImage(null);
        lockoutDialog.setModal(true);
        lockoutDialog.setResizable(false);
        lockoutDialog.getContentPane().setLayout(null);

        lockoutLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lockoutLabel1.setText("Do you still want to continue?");
        lockoutDialog.getContentPane().add(lockoutLabel1);
        lockoutLabel1.setBounds(80, 60, 290, 30);

        lockoutLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lockoutLabel2.setText("The user account will be lockout. ");
        lockoutDialog.getContentPane().add(lockoutLabel2);
        lockoutLabel2.setBounds(80, 30, 220, 30);

        confirmLockoutButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        confirmLockoutButton.setText("Confirm");
        confirmLockoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmLockoutButtonActionPerformed(evt);
            }
        });
        lockoutDialog.getContentPane().add(confirmLockoutButton);
        confirmLockoutButton.setBounds(80, 110, 100, 30);

        cancelLockoutButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cancelLockoutButton.setText("Cancel");
        cancelLockoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelLockoutButtonActionPerformed(evt);
            }
        });
        lockoutDialog.getContentPane().add(cancelLockoutButton);
        cancelLockoutButton.setBounds(270, 110, 100, 30);

        unlockDialog.setTitle("Attention");
        unlockDialog.setIconImage(null);
        unlockDialog.setModal(true);
        unlockDialog.setResizable(false);
        unlockDialog.getContentPane().setLayout(null);

        unlockLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        unlockLabel2.setText("Do you still want to continue?");
        unlockDialog.getContentPane().add(unlockLabel2);
        unlockLabel2.setBounds(80, 60, 290, 30);

        unlockLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        unlockLabel1.setText("The user account will be unlocked. ");
        unlockDialog.getContentPane().add(unlockLabel1);
        unlockLabel1.setBounds(80, 30, 220, 30);

        confirmUnlockButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        confirmUnlockButton.setText("Confirm");
        confirmUnlockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmUnlockButtonActionPerformed(evt);
            }
        });
        unlockDialog.getContentPane().add(confirmUnlockButton);
        confirmUnlockButton.setBounds(80, 110, 100, 30);

        cancelUnlockButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cancelUnlockButton.setText("Cancel");
        cancelUnlockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelUnlockButtonActionPerformed(evt);
            }
        });
        unlockDialog.getContentPane().add(cancelUnlockButton);
        cancelUnlockButton.setBounds(270, 110, 100, 30);

        confirmDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        confirmDialog.setTitle("Attention");
        confirmDialog.setAlwaysOnTop(true);
        confirmDialog.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        confirmDialog.setIconImage(null);
        confirmDialog.setName("completeDialog"); // NOI18N
        confirmDialog.setResizable(false);
        confirmDialog.getContentPane().setLayout(null);

        confirmPanel.setMaximumSize(new java.awt.Dimension(285, 190));
        confirmPanel.setPreferredSize(new java.awt.Dimension(285, 190));
        confirmPanel.setLayout(null);

        confirmDialogButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        confirmDialogButton.setText("Confirm");
        confirmDialogButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmDialogButtonActionPerformed(evt);
            }
        });
        confirmPanel.add(confirmDialogButton);
        confirmDialogButton.setBounds(90, 80, 100, 30);

        confirmInfoLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        confirmPanel.add(confirmInfoLabel);
        confirmInfoLabel.setBounds(70, 30, 150, 30);

        confirmDialog.getContentPane().add(confirmPanel);
        confirmPanel.setBounds(0, 0, 285, 190);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Users Found");
        setName("frame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(450, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        panel.setMaximumSize(new java.awt.Dimension(450, 300));
        panel.setMinimumSize(new java.awt.Dimension(0, 0));
        panel.setLayout(null);

        cancelButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        panel.add(cancelButton);
        cancelButton.setBounds(320, 200, 120, 25);

        userTable.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "Gender", "ID", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(userTable);

        panel.add(jScrollPane3);
        jScrollPane3.setBounds(10, 10, 430, 180);

        lockoutButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lockoutButton.setText("Lockout");
        lockoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockoutButtonActionPerformed(evt);
            }
        });
        panel.add(lockoutButton);
        lockoutButton.setBounds(10, 200, 120, 25);

        resetButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        resetButton.setText("Reset Password");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        panel.add(resetButton);
        resetButton.setBounds(10, 230, 120, 25);

        unlockButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        unlockButton.setText("Unlock");
        unlockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unlockButtonActionPerformed(evt);
            }
        });
        panel.add(unlockButton);
        unlockButton.setBounds(170, 200, 120, 25);

        mergeButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        mergeButton.setText("Merge");
        mergeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mergeButtonActionPerformed(evt);
            }
        });
        panel.add(mergeButton);
        mergeButton.setBounds(170, 230, 120, 25);

        assignButton.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        assignButton.setText("Assign");
        assignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignButtonActionPerformed(evt);
            }
        });
        panel.add(assignButton);
        assignButton.setBounds(320, 230, 120, 25);

        getContentPane().add(panel);
        panel.setBounds(0, 0, 450, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        AdminMain adminMain = new AdminMain();
	adminMain.AdminMainVisible();
	this.dispose();        
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void lockoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockoutButtonActionPerformed
        if(userTable.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(null, "Please select one user!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
            int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
            lockoutDialog.setSize(450, 200);
            lockoutDialog.setLocation((screenWidth - lockoutDialog.getSize().width) / 2,(screenHeight - lockoutDialog.getSize().height) / 2);    
            lockoutDialog.setVisible(true);
        }
    }//GEN-LAST:event_lockoutButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        if(userTable.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(null, "Please select one user!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
            int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
            resetDialog.setSize(450, 200);
            resetDialog.setLocation((screenWidth - resetDialog.getSize().width) / 2,(screenHeight - resetDialog.getSize().height) / 2);    
            resetDialog.setVisible(true);
        }
    }//GEN-LAST:event_resetButtonActionPerformed

    private void unlockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unlockButtonActionPerformed
        if(userTable.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(null, "Please select one user!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
            int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
            unlockDialog.setSize(450, 200);
            unlockDialog.setLocation((screenWidth - unlockDialog.getSize().width) / 2,(screenHeight - unlockDialog.getSize().height) / 2);    
            unlockDialog.setVisible(true);
        }
    }//GEN-LAST:event_unlockButtonActionPerformed

    private void mergeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mergeButtonActionPerformed
        if(userTable.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(null, "Please select one user!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            Find find = new Find(MERGE);
            find.FindVisible();
            this.dispose();
        }
    }//GEN-LAST:event_mergeButtonActionPerformed

    private void cancelResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelResetButtonActionPerformed
        resetDialog.dispose();
    }//GEN-LAST:event_cancelResetButtonActionPerformed

    private void confirmResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmResetButtonActionPerformed
        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
	int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
	confirmDialog.setSize(285, 190);
        confirmDialog.setLocation((screenWidth - confirmDialog.getSize().width) / 2,(screenHeight - confirmDialog.getSize().height) / 2);        
        confirmInfoLabel.setText("Password reset complete.");
        confirmDialog.setVisible(true);
        resetDialog.dispose();
    }//GEN-LAST:event_confirmResetButtonActionPerformed

    private void confirmDialogButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmDialogButtonActionPerformed
        // TODO add your handling code here:
        confirmDialog.dispose();
    }//GEN-LAST:event_confirmDialogButtonActionPerformed

    private void confirmLockoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmLockoutButtonActionPerformed
        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
	int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
	confirmDialog.setSize(285, 190);
        confirmDialog.setLocation((screenWidth - confirmDialog.getSize().width) / 2,(screenHeight - confirmDialog.getSize().height) / 2);        
        confirmInfoLabel.setText("Account lockout complete.");
        confirmDialog.setVisible(true);
//        confirmDialog.requestFocus();
        lockoutDialog.dispose();
    }//GEN-LAST:event_confirmLockoutButtonActionPerformed

    private void cancelLockoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelLockoutButtonActionPerformed
        lockoutDialog.dispose();
    }//GEN-LAST:event_cancelLockoutButtonActionPerformed

    private void confirmUnlockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmUnlockButtonActionPerformed
        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
	int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
	confirmDialog.setSize(285, 190);
        confirmDialog.setLocation((screenWidth - confirmDialog.getSize().width) / 2,(screenHeight - confirmDialog.getSize().height) / 2);        
        confirmInfoLabel.setText("Account unlock complete.");
        confirmDialog.setVisible(true);
//        confirmDialog.requestFocus();
        unlockDialog.dispose();
    }//GEN-LAST:event_confirmUnlockButtonActionPerformed

    private void cancelUnlockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelUnlockButtonActionPerformed
        unlockDialog.dispose();
    }//GEN-LAST:event_cancelUnlockButtonActionPerformed

    private void assignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignButtonActionPerformed
        if(userTable.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(null, "Please select one user!", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            Find find = new Find(ASSIGN);
            find.FindVisible();
            this.dispose();
        }
    }//GEN-LAST:event_assignButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelLockoutButton;
    private javax.swing.JButton cancelResetButton;
    private javax.swing.JButton cancelUnlockButton;
    private javax.swing.JDialog confirmDialog;
    private javax.swing.JButton confirmDialogButton;
    private javax.swing.JLabel confirmInfoLabel;
    private javax.swing.JButton confirmLockoutButton;
    private javax.swing.JPanel confirmPanel;
    private javax.swing.JButton confirmResetButton;
    private javax.swing.JButton confirmUnlockButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton3;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton lockoutButton;
    private javax.swing.JDialog lockoutDialog;
    private javax.swing.JLabel lockoutLabel1;
    private javax.swing.JLabel lockoutLabel2;
    private javax.swing.JButton mergeButton;
    private javax.swing.JPanel panel;
    private javax.swing.JButton resetButton;
    private javax.swing.JDialog resetDialog;
    private javax.swing.JLabel resetLabel1;
    private javax.swing.JLabel resetLabel2;
    private javax.swing.JButton unlockButton;
    private javax.swing.JDialog unlockDialog;
    private javax.swing.JLabel unlockLabel1;
    private javax.swing.JLabel unlockLabel2;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
