

package GUI;
import java.awt.*;
import java.util.concurrent.TimeUnit;
/**
 *
 * @author shaosh
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
        int screenWidth = (int)Toolkit.getDefaultToolkit().getScreenSize().getWidth();
	int screenHeight = (int)Toolkit.getDefaultToolkit().getScreenSize().getHeight();
	this.setLocation((screenWidth - this.getSize().width) / 2,(screenHeight - this.getSize().height) / 2); 
//        try {
//            TimeUnit.SECONDS.sleep(3);
//        } catch (InterruptedException e) {
//            // TODO Auto-generated catch block
//            e.printStackTrace();
//        }
//        this.setVisible(false);
        
    }
    public void WelcomeVisible(){
        this.setVisible(true);		
        SignIn signIn =  new SignIn();
        try {
            TimeUnit.SECONDS.sleep(3);
        } catch (InterruptedException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
	signIn.SignInVisible();
 //       this.setVisible(false);
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Doctor's Note");
        setName("frame"); // NOI18N
        setResizable(false);

        panel.setLayout(null);

        label.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("Welcome to Doctor's Note!");
        label.setPreferredSize(new java.awt.Dimension(200, 30));
        panel.add(label);
        label.setBounds(40, 40, 365, 30);

        infoLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        infoLabel.setText("v1.2       Ravenware");
        panel.add(infoLabel);
        infoLabel.setBounds(160, 90, 145, 21);

        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/raven.png"))); // NOI18N
        panel.add(logoLabel);
        logoLabel.setBounds(150, 120, 160, 140);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel label;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
